import type { Metadata } from "next";
import "./globals.css";
import { poppin } from "./constants";



export const metadata: Metadata = {
  title: "Calender",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${poppin.className}`}
      >
        {children}
      </body>
    </html>
  );
}
