import type { Metadata } from "next";
import "./globals.css";
import { poppin } from "./constants";
import { ThemeProvider } from "./components/ui";



export const metadata: Metadata = {
  title: "Calender",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${poppin.className}`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
